function factor = factorLocalAugmentedSystem(A)
%FACTORLOCALAUGMENTEDSYSTEM Factor a small local RBF/poly system.
%   LU is the fast default. QR fallback is handled by
%   solveAndFactorLocalAugmentedSystem after checking both the triangular
%   factor conditioning and the actual solve residual.

[L, U, P] = lu(A, 'vector');
reciprocalCondition = rcond(U);
factor = struct( ...
    'kind', "lu", ...
    'L', L, ...
    'U', U, ...
    'P', P, ...
    'Q', [], ...
    'R', [], ...
    'E', [], ...
    'rank', size(A, 2), ...
    'reciprocalCondition', reciprocalCondition);
end
