function diffusion_solver_checks()
%DIFFUSION_SOLVER_CHECKS Basic checks for the transient diffusion stepper.

domain = buildTestDomain();
nu = 0.25;
dt = 0.02;
Xphys = domain.getIntBdryNodes();
uExact = @(time, X) exp(-time) .* (X(:, 1).^2 + X(:, 2).^2);
forcing = @(nuValue, time, X) -exp(-time) .* (X(:, 1).^2 + X(:, 2).^2) - 4 * nuValue * exp(-time);
neuCoeffFixed = @(Xb) zeros(size(Xb, 1), 1);
dirCoeffFixed = @(Xb) ones(size(Xb, 1), 1);
bc = @(NeuCoeffs, DirCoeffs, nr, time, Xb) uExact(time, Xb); %#ok<INUSD>

wlsSolver = kp.solvers.DiffusionSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'wls', ...
    'BCStencil', 'wls');
wlsSolver.init(domain, 3, dt, nu);
wlsSolver.setInitialState(uExact(0, Xphys));
u1 = wlsSolver.bdf1Step(dt, forcing, neuCoeffFixed, dirCoeffFixed, bc);
assert(max(abs(u1 - uExact(dt, Xphys))) < 3e-1, ...
    'WLS BDF1 diffusion step should track the manufactured solution to modest accuracy.');
u2 = wlsSolver.bdf2Step(2 * dt, forcing, neuCoeffFixed, dirCoeffFixed, bc);
assert(max(abs(u2 - uExact(2 * dt, Xphys))) < 3.5e-1, ...
    'WLS BDF2 diffusion step should track the manufactured solution to modest accuracy.');
u3 = wlsSolver.bdf3Step(3 * dt, forcing, neuCoeffFixed, dirCoeffFixed, bc);
assert(max(abs(u3 - uExact(3 * dt, Xphys))) < 4e-1, ...
    'WLS BDF3 diffusion step should track the manufactured solution to modest accuracy.');

rbfSolver = kp.solvers.DiffusionSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'rbf', ...
    'BCStencil', 'rbf');
rbfSolver.init(domain, 3, dt, nu);
rbfSolver.setInitialState(uExact(0, Xphys));
u1_rbf = rbfSolver.bdf1Step(dt, forcing, ...
    @(time, Xb) zeros(size(Xb, 1), 1), ...
    @(time, Xb) ones(size(Xb, 1), 1), ...
    bc);
assert(max(abs(u1_rbf - uExact(dt, Xphys))) < 7e-1, ...
    'RBF BDF1 diffusion step should track the manufactured solution to modest accuracy.');

historySolver = kp.solvers.DiffusionSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'wls', ...
    'BCStencil', 'wls');
historySolver.init(domain, 3, dt, nu);
historySolver.setStateHistory(uExact(0, Xphys), uExact(dt, Xphys), uExact(2 * dt, Xphys));
stateNow = historySolver.currentPhysicalState();
assert(max(abs(stateNow - uExact(2 * dt, Xphys))) < 1e-12, ...
    'currentPhysicalState should return the newest stored physical state.');

disp('diffusion solver checks passed');
end

function domain = buildTestDomain()
t = linspace(0, 2*pi, 80).';
t(end) = [];
curve = [cos(t), 0.8 * sin(t)];

surface = kp.geometry.EmbeddedSurface();
surface.setDataSites(curve);
surface.buildClosedGeometricModelPS(2, 0.06, size(curve, 1));
surface.buildLevelSetFromGeometricModel([]);

generator = kp.nodes.DomainNodeGenerator();
domain = generator.buildDomainDescriptorFromGeometry(surface, 0.1, ...
    'Seed', 17, ...
    'StripCount', 5, ...
    'DoOuterRefinement', true, ...
    'OuterFractionOfh', 0.5, ...
    'OuterRefinementZoneSizeAsMultipleOfh', 2.0);
end
