function moving_surface_rbc_capstone_checks()
%MOVING_SURFACE_RBC_CAPSTONE_CHECKS Validate the saved 3D capstone result.

root = fileparts(fileparts(mfilename('fullpath')));
saved = load(fullfile(root, 'moving_surface_adr_tp_rbc_capstone.mat'), 'capstone');
capstone = saved.capstone;
result = capstone.results;
solveStats = result.solveStats{1};

assert(result.xi == 6 && result.N == 2562 && result.nsteps == 20034, ...
    'The saved capstone discretization metadata changed unexpectedly.');
assert(all(isfinite(capstone.final.concentration)), ...
    'The saved final concentration contains non-finite values.');
assert(min(capstone.final.concentration) > 0, ...
    'The saved source-free tracer must remain positive.');
assert(max(capstone.final.concentration) < 1.2, ...
    'The saved tracer contains an unexpectedly large final overshoot.');
assert(result.balanceRelResidual < 1.0e-12, ...
    'The saved capstone does not satisfy discrete mass balance.');
assert(result.massCorrectionMaxRelative < 1.0e-3, ...
    'The mass projection is making an unexpectedly large correction.');
assert(solveStats.gmresFailures == 0, ...
    'The saved capstone contains a failed global linear solve.');
assert(result.maxQuality < 2.3 && result.numRearrangements == 0, ...
    'The saved area-uniform marker cloud should remain below the remap threshold.');
assert(capstone.velocityInterpolation.relativeRMS < 1.0e-3, ...
    'The saved trajectory velocity check is too large.');

disp('moving-surface RBC capstone checks passed');
fprintf('  concentration range: [%.3e, %.3e]\n', ...
    min(capstone.final.concentration), max(capstone.final.concentration));
fprintf('  mass residual / max correction: %.3e / %.3e\n', ...
    result.balanceRelResidual, result.massCorrectionMaxRelative);
end
