function poisson_solver_checks()
%POISSON_SOLVER_CHECKS Basic checks for the KernelPack-shaped Poisson solver.

domain = buildTestDomain();
uExact = @(X) X(:, 1).^2 + X(:, 2).^2;
uTrue = uExact(domain.getIntBdryNodes());

wlsSolver = kp.solvers.PoissonSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'wls', ...
    'BCStencil', 'wls');
wlsSolver.init(domain, 3);
wlsResult = wlsSolver.solve( ...
    @(Xeq) -4 * ones(size(Xeq, 1), 1), ...
    @(Xb) zeros(size(Xb, 1), 1), ...
    @(Xb) ones(size(Xb, 1), 1), ...
    @(NeuCoeffs, DirCoeffs, nr, Xb) uExact(Xb)); %#ok<INUSD>
assert(max(abs(wlsResult.u - uTrue)) < 2.5e-1, ...
    'WLS Poisson solve should reproduce the quadratic Dirichlet problem to modest accuracy.');

rbfSolver = kp.solvers.PoissonSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'rbf', ...
    'BCStencil', 'rbf');
rbfSolver.init(domain, 3);
rbfResult = rbfSolver.solve( ...
    @(Xeq) -4 * ones(size(Xeq, 1), 1), ...
    @(Xb) zeros(size(Xb, 1), 1), ...
    @(Xb) ones(size(Xb, 1), 1), ...
    @(NeuCoeffs, DirCoeffs, nr, Xb) uExact(Xb)); %#ok<INUSD>
assert(max(abs(rbfResult.u - uTrue)) < 6e-1, ...
    'RBF Poisson solve should reproduce the quadratic Dirichlet problem to modest accuracy.');

zeroNeuSolver = kp.solvers.PoissonSolver( ...
    'LapAssembler', 'fd', ...
    'BCAssembler', 'fd', ...
    'LapStencil', 'wls', ...
    'BCStencil', 'wls');
zeroNeuSolver.init(domain, 3);
zeroNeuResult = zeroNeuSolver.solve( ...
    @(Xeq) zeros(size(Xeq, 1), 1), ...
    @(Xb) ones(size(Xb, 1), 1), ...
    @(Xb) zeros(size(Xb, 1), 1), ...
    @(NeuCoeffs, DirCoeffs, nr, Xb) zeros(size(Xb, 1), 1)); %#ok<INUSD>
assert(zeroNeuResult.UsedNullspaceAugmentation, ...
    'Pure Neumann solves should use nullspace augmentation.');
assert(max(abs(zeroNeuResult.u)) < 1e-8, ...
    'Zero-Neumann zero-source solve should return the zero solution under the mean constraint.');
assert(numel(wlsResult.u) == domain.getNumIntBdryNodes(), ...
    'PoissonSolver should return only the physical target state.');

assert(zeroNeuSolver.lastSolveUsedNullspace(), ...
    'lastSolveUsedNullspace should reflect the most recent solve path.');

disp('poisson solver checks passed');
end

function domain = buildTestDomain()
t = linspace(0, 2*pi, 80).';
t(end) = [];
curve = [cos(t), 0.8 * sin(t)];

surface = kp.geometry.EmbeddedSurface();
surface.setDataSites(curve);
surface.buildClosedGeometricModelPS(2, 0.06, size(curve, 1));
surface.buildLevelSetFromGeometricModel([]);

generator = kp.nodes.DomainNodeGenerator();
domain = generator.buildDomainDescriptorFromGeometry(surface, 0.1, ...
    'Seed', 17, ...
    'StripCount', 5, ...
    'DoOuterRefinement', true, ...
    'OuterFractionOfh', 0.5, ...
    'OuterRefinementZoneSizeAsMultipleOfh', 2.0);
end
