function run_public_checks()
%RUN_PUBLIC_CHECKS Run the data-independent public verification suite.

checks = { ...
    @geometry_checks, ...
    @nodes_checks, ...
    @poly_checks, ...
    @rbffd_checks, ...
    @dual_node_checks, ...
    @poisson_solver_checks, ...
    @variable_poisson_solver_checks, ...
    @diffusion_solver_checks, ...
    @pu_diffusion_checks, ...
    @multispecies_pu_diffusion_checks, ...
    @meshfree_geometric_multilevel_checks, ...
    @divfree_interp_checks, ...
    @manifold_tangent_plane_checks, ...
    @manifold_diffmat_update_checks, ...
    @manifold_hyperviscosity_checks, ...
    @manifold_mean_curvature_flow_checks, ...
    @manifold_convergence_results_checks, ...
    @mip_package_checks};

for k = 1:numel(checks)
    fprintf('\n[%d/%d] %s\n', k, numel(checks), func2str(checks{k}));
    checks{k}();
end

fprintf('\nAll public checks passed.\n');
end
