function study = moving_surface_adr_tp_literature_threshold_sweep(varargin)
%MOVING_SURFACE_ADR_TP_LITERATURE_THRESHOLD_SWEEP Coarsest xi=6 literature match.
%   Runs the final moving-surface ADR configuration on every directly
%   comparable manufactured literature benchmark and stops each case at the
%   coarsest point cloud whose error is below the published target.

parser = inputParser();
parser.addParameter('Cases', ["de_stationary_sphere", "de_moving_ellipsoid", ...
    "ox_translating_sphere", "ox_rotating_sphere", "ox_shrinking_sphere"]);
parser.addParameter('Xi', 6, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('NVals', [96, 144, 196, 256, 384, 576, 768, 1024, 1600, 2500, 3600, 4900], ...
    @(x) isnumeric(x) && isvector(x));
parser.addParameter('DtScale', 0.05, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('UseRearrangement', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('QualityThreshold', 1.55, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('QualitySamples', 9, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('PredictiveLookaheadSteps', 3, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('MinStepsBetweenRearrangements', 8, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('RearrangementTransferMode', "localTp", @(x) isstring(x) || ischar(x));
parser.addParameter('MassCorrectionMode', "balance", @(x) isstring(x) || ischar(x));
parser.addParameter('ExactStartup', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('GlobalGMRESTolerance', 1.0e-12, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
parser.addParameter('StopAtFirstSuccess', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('ContinueOnError', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('SaveAfterEach', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('WarmParallelPool', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('OutputPrefix', fullfile(pwd, ...
    'moving_surface_adr_tp_literature_threshold_xi6'));
parser.parse(varargin{:});
opts = parser.Results;

if opts.WarmParallelPool
    warmParallelPool();
end

cases = string(opts.Cases(:).');
nVals = unique(round(opts.NVals(:).'), 'stable');
rows = repmat(emptyRow(), 0, 1);
inventory = repmat(emptyBenchmarkRow(), numel(cases), 1);
rowIndex = 0;

for icase = 1:numel(cases)
    caseName = cases(icase);
    [problem, benchmark] = moving_surface_adr_tp_literature_problem(caseName);
    inventory(icase) = benchmarkRow(benchmark);
    fprintf('\nLiterature threshold case=%s target=%s <= %.6e\n', ...
        caseName, benchmark.targetMetric, benchmark.targetValue);

    caseSucceeded = false;
    for N = nVals
        rowIndex = rowIndex + 1;
        rows(rowIndex, 1) = runOneCandidate(problem, benchmark, opts, N);
        if opts.SaveAfterEach
            study = buildStudy(rows, inventory, opts);
            saveStudy(study, opts.OutputPrefix);
        end

        if rows(rowIndex).success
            caseSucceeded = true;
            if opts.StopAtFirstSuccess
                break;
            end
        end
    end

    if ~caseSucceeded
        fprintf('  no threshold success found for %s over supplied N values\n', caseName);
    end
end

study = buildStudy(rows, inventory, opts);
saveStudy(study, opts.OutputPrefix);
end

function warmParallelPool()
pool = gcp('nocreate');
if isempty(pool)
    parpool('Processes');
end
end

function row = runOneCandidate(problem, benchmark, opts, N)
row = emptyRow();
row.caseName = benchmark.caseName;
row.sourceKey = benchmark.sourceKey;
row.benchmark = benchmark.benchmark;
row.publishedMethod = benchmark.publishedMethod;
row.targetMetric = benchmark.targetMetric;
row.targetValue = benchmark.targetValue;
row.targetDescription = benchmark.targetDescription;
row.publishedH = benchmark.publishedH;
row.publishedDt = benchmark.publishedDt;
row.finalTime = benchmark.finalTime;
row.xi = opts.Xi;
row.N = N;
row.sqrtN = sqrt(N);
row.dtScale = opts.DtScale;
row.normalMode = "calibratedSbf";
row.rearrangementPolicy = "adaptiveQuality";

fprintf('  candidate N=%d\n', N);
try
    tic;
    quality = qualityDiagnostics(problem, N, benchmark.finalTime, ...
        opts.QualityThreshold, round(opts.QualitySamples));
    result = kp.manifold.runLagrangianMovingADRConvergence( ...
        problem, opts.Xi, N, opts.DtScale, ...
        'Mu', 1.0, ...
        'FinalTime', benchmark.finalTime, ...
        'DiffMatUpdateMethod', 'defect', ...
        'DefectTolerance', 1.0e-6, ...
        'MaxDefectIterations', 4, ...
        'NeighborUpdateMode', "periodic", ...
        'NeighborSearchInterval', 5, ...
        'SpectrumCheck', false, ...
        'HyperviscosityUpdateMode', 'adaptiveGeometry', ...
        'HyperviscosityDriftTolerance', 0.05, ...
        'MaxHyperviscositySkippedSteps', 5, ...
        'NormalMode', 'calibratedSbf', ...
        'NormalNeighborCount', 32, ...
        'GlobalSBFNormalDegree', 7, ...
        'GlobalSBFNormalOrder', 8, ...
        'GlobalSBFBalanceSafety', 0.1, ...
        'GlobalSBFControlPointScale', 1 / 3, ...
        'GlobalSBFMinControlPointCount', 48, ...
        'RecordMassDiagnostics', true, ...
        'TrackTimeErrors', true, ...
        'ExactStartup', opts.ExactStartup, ...
        'GlobalSolveMethod', "gmresIluDefect", ...
        'GlobalGMRESTolerance', opts.GlobalGMRESTolerance, ...
        'GlobalGMRESRestart', 40, ...
        'GlobalGMRESMaxIterations', 30, ...
        'GlobalDefectSweeps', 4, ...
        'GlobalILUDropTolerance', 1.0e-4, ...
        'UseRearrangement', opts.UseRearrangement, ...
        'QualityThreshold', opts.QualityThreshold, ...
        'PredictiveLookaheadSteps', opts.PredictiveLookaheadSteps, ...
        'MinStepsBetweenRearrangements', opts.MinStepsBetweenRearrangements, ...
        'RearrangementTransferMode', opts.RearrangementTransferMode, ...
        'MassCorrectionMode', opts.MassCorrectionMode);
    row.elapsedSeconds = toc;
    row.status = "ok";
    row.message = "";
    row.h = result.h;
    row.dt = result.dt;
    row.nsteps = result.nsteps;
    row.finalRelL2Error = result.finalRelL2Error;
    row.finalAbsL2Error = result.finalAbsL2Error;
    row.maxRelL2Error = result.maxRelL2Error;
    row.maxAbsL2Error = result.maxAbsL2Error;
    row.timeRelL2L2Error = result.timeRelL2L2Error;
    row.timeAbsL2L2Error = result.timeAbsL2L2Error;
    row.massRelError = result.massRelError;
    row.balanceRelResidual = result.balanceRelResidual;
    row.massCorrectionSteps = result.massCorrectionSteps;
    row.massCorrectionMaxRelative = result.massCorrectionMaxRelative;
    row.massCorrectionMaxPointShift = result.massCorrectionMaxPointShift;
    row.normalRMSAngle = result.normalRMSAngle;
    row.normalMaxAngle = result.normalMaxAngle;
    row.normalControlPointCount = result.normalControlPointCount;
    row.normalControlPointFraction = result.normalControlPointFraction;
    row.normalControlFillDistance = result.normalControlFillDistance;
    row.maxQuality = result.maxQuality;
    row.initialQuality = result.initialQuality;
    row.finalQuality = result.finalQuality;
    row.numRearrangements = result.numRearrangements;
    if row.numRearrangements > 0
        row.rearrangementStatus = "rearranged";
    elseif quality.triggered
        row.rearrangementStatus = "triggerMissed";
    else
        row.rearrangementStatus = "enabledNotTriggered";
    end
    row.metricValue = metricValue(result, benchmark.targetMetric);
    row.success = isfinite(row.metricValue) && row.metricValue <= benchmark.targetValue;
    row.relativeToPublished = row.metricValue / benchmark.targetValue;
    row.effectiveSpacingRatio = row.h / benchmark.publishedH;
    row.timeStepRatio = row.dt / benchmark.publishedDt;
    stats = result.updateStats{1};
    row.updateDirect = stats.direct;
    row.updateDefectCorrected = stats.defectCorrected;
    row.updateFallback = stats.defectFailedRefactored;
    solveStats = result.solveStats{1};
    row.iluRefreshes = solveStats.iluRefreshes;
    row.gmresSolves = solveStats.gmresSolves;
    row.gmresIterations = solveStats.gmresIterations;
    row.hyperviscosityMinPower = stats.minHyperviscosityPower;
    row.hyperviscosityMaxPower = stats.maxHyperviscosityPower;
    fprintf('    %s=%.6e target=%.6e ratio=%.3f h/h_lit=%.2f dt/dt_lit=%.2f quality=%.2f success=%d\n', ...
        row.targetMetric, row.metricValue, row.targetValue, row.relativeToPublished, ...
        row.effectiveSpacingRatio, row.timeStepRatio, row.maxQuality, row.success);
catch ME
    row.elapsedSeconds = toc;
    row.status = "failed";
    row.message = string(ME.message);
    fprintf('    FAILED: %s\n', ME.message);
    if ~opts.ContinueOnError
        rethrow(ME);
    end
end
end

function value = metricValue(result, metricName)
switch string(metricName)
    case "maxAbsL2Error"
        value = result.maxAbsL2Error;
    case "timeAbsL2L2Error"
        value = result.timeAbsL2L2Error;
    case "finalAbsL2Error"
        value = result.finalAbsL2Error;
    case "finalRelL2Error"
        value = result.finalRelL2Error;
    otherwise
        error('kp:examples:BadLiteratureMetric', ...
            'Unknown literature comparison metric "%s".', metricName);
end
end

function quality = qualityDiagnostics(problem, N, T, threshold, numSamples)
numSamples = max(2, numSamples);
times = linspace(0, T, numSamples);
values = zeros(numSamples, 1);
for k = 1:numSamples
    geom = problem.geometry(N, times(k));
    values(k) = pointQuality(geom.X);
end
quality = struct( ...
    'times', times(:), ...
    'values', values, ...
    'initialQuality', values(1), ...
    'finalQuality', values(end), ...
    'maxQuality', max(values), ...
    'triggered', max(values) > threshold);
end

function q = pointQuality(X)
tree = KDTreeSearcher(X);
[~, d] = knnsearch(tree, X, 'K', 2);
nearest = d(:, 2);
q = max(nearest) / max(min(nearest), eps);
end

function study = buildStudy(rows, inventory, opts)
T = struct2table(rows);
study = struct();
study.table = T;
study.inventory = struct2table(inventory);
study.summary = summarizeCoarsest(T);
study.xi = opts.Xi;
study.dtScale = opts.DtScale;
study.qualityThreshold = opts.QualityThreshold;
study.normalMode = "calibratedSbf";
study.diffMatUpdateMethod = "defect";
study.hyperviscosityUpdateMode = "adaptiveGeometry";
study.globalSolveMethod = "gmresIluDefect";
study.massCorrectionMode = string(opts.MassCorrectionMode);
end

function summary = summarizeCoarsest(T)
if isempty(T)
    summary = table();
    return;
end
cases = unique(T.caseName, 'stable').';
rows = repmat(emptySummaryRow(), 0, 1);
for caseName = cases
    S = T(T.caseName == caseName & T.success, :);
    if isempty(S)
        S = T(T.caseName == caseName, :);
        if isempty(S)
            continue;
        end
        [~, idx] = max(S.N);
        chosen = S(idx, :);
        ok = false;
    else
        [~, idx] = min(S.N);
        chosen = S(idx, :);
        ok = true;
    end
    row = emptySummaryRow();
    row.caseName = chosen.caseName;
    row.benchmark = chosen.benchmark;
    row.sourceKey = chosen.sourceKey;
    row.success = ok;
    row.N = chosen.N;
    row.sqrtN = chosen.sqrtN;
    row.h = chosen.h;
    row.dt = chosen.dt;
    row.nsteps = chosen.nsteps;
    row.targetMetric = chosen.targetMetric;
    row.targetValue = chosen.targetValue;
    row.metricValue = chosen.metricValue;
    row.relativeToPublished = chosen.relativeToPublished;
    row.effectiveSpacingRatio = chosen.effectiveSpacingRatio;
    row.timeStepRatio = chosen.timeStepRatio;
    row.massRelError = chosen.massRelError;
    row.balanceRelResidual = chosen.balanceRelResidual;
    row.massCorrectionSteps = chosen.massCorrectionSteps;
    row.massCorrectionMaxRelative = chosen.massCorrectionMaxRelative;
    row.massCorrectionMaxPointShift = chosen.massCorrectionMaxPointShift;
    row.maxQuality = chosen.maxQuality;
    row.normalControlPointCount = chosen.normalControlPointCount;
    row.normalControlPointFraction = chosen.normalControlPointFraction;
    row.rearrangementStatus = chosen.rearrangementStatus;
    row.elapsedSeconds = chosen.elapsedSeconds;
    rows(end + 1, 1) = row; %#ok<AGROW>
end
summary = struct2table(rows);
end

function saveStudy(study, outputPrefix)
save(string(outputPrefix) + ".mat", 'study');
writetable(study.table, string(outputPrefix) + "_all.csv");
writetable(study.summary, string(outputPrefix) + "_summary.csv");
writetable(study.inventory, string(outputPrefix) + "_inventory.csv");
end

function row = benchmarkRow(benchmark)
row = emptyBenchmarkRow();
row.caseName = benchmark.caseName;
row.sourceKey = benchmark.sourceKey;
row.benchmark = benchmark.benchmark;
row.setup = benchmark.setup;
row.publishedMethod = benchmark.publishedMethod;
row.targetMetric = benchmark.targetMetric;
row.targetValue = benchmark.targetValue;
row.targetDescription = benchmark.targetDescription;
row.publishedH = benchmark.publishedH;
row.publishedDt = benchmark.publishedDt;
row.finalTime = benchmark.finalTime;
end

function row = emptyBenchmarkRow()
row = struct( ...
    'caseName', "", ...
    'sourceKey', "", ...
    'benchmark', "", ...
    'setup', "", ...
    'publishedMethod', "", ...
    'targetMetric', "", ...
    'targetValue', NaN, ...
    'targetDescription', "", ...
    'publishedH', NaN, ...
    'publishedDt', NaN, ...
    'finalTime', NaN);
end

function row = emptySummaryRow()
row = struct( ...
    'caseName', "", ...
    'benchmark', "", ...
    'sourceKey', "", ...
    'success', false, ...
    'N', NaN, ...
    'sqrtN', NaN, ...
    'h', NaN, ...
    'dt', NaN, ...
    'nsteps', NaN, ...
    'targetMetric', "", ...
    'targetValue', NaN, ...
    'metricValue', NaN, ...
    'relativeToPublished', NaN, ...
    'effectiveSpacingRatio', NaN, ...
    'timeStepRatio', NaN, ...
    'massRelError', NaN, ...
    'balanceRelResidual', NaN, ...
    'massCorrectionSteps', NaN, ...
    'massCorrectionMaxRelative', NaN, ...
    'massCorrectionMaxPointShift', NaN, ...
    'maxQuality', NaN, ...
    'normalControlPointCount', NaN, ...
    'normalControlPointFraction', NaN, ...
    'rearrangementStatus', "", ...
    'elapsedSeconds', NaN);
end

function row = emptyRow()
row = struct( ...
    'caseName', "", ...
    'sourceKey', "", ...
    'benchmark', "", ...
    'publishedMethod', "", ...
    'targetMetric', "", ...
    'targetDescription', "", ...
    'targetValue', NaN, ...
    'publishedH', NaN, ...
    'publishedDt', NaN, ...
    'finalTime', NaN, ...
    'xi', NaN, ...
    'N', NaN, ...
    'sqrtN', NaN, ...
    'h', NaN, ...
    'dt', NaN, ...
    'nsteps', NaN, ...
    'dtScale', NaN, ...
    'normalMode', "", ...
    'rearrangementPolicy', "", ...
    'rearrangementStatus', "", ...
    'numRearrangements', NaN, ...
    'metricValue', NaN, ...
    'success', false, ...
    'relativeToPublished', NaN, ...
    'effectiveSpacingRatio', NaN, ...
    'timeStepRatio', NaN, ...
    'finalRelL2Error', NaN, ...
    'finalAbsL2Error', NaN, ...
    'maxRelL2Error', NaN, ...
    'maxAbsL2Error', NaN, ...
    'timeRelL2L2Error', NaN, ...
    'timeAbsL2L2Error', NaN, ...
    'massRelError', NaN, ...
    'balanceRelResidual', NaN, ...
    'massCorrectionSteps', NaN, ...
    'massCorrectionMaxRelative', NaN, ...
    'massCorrectionMaxPointShift', NaN, ...
    'normalRMSAngle', NaN, ...
    'normalMaxAngle', NaN, ...
    'normalControlPointCount', NaN, ...
    'normalControlPointFraction', NaN, ...
    'normalControlFillDistance', NaN, ...
    'initialQuality', NaN, ...
    'finalQuality', NaN, ...
    'maxQuality', NaN, ...
    'updateDirect', NaN, ...
    'updateDefectCorrected', NaN, ...
    'updateFallback', NaN, ...
    'hyperviscosityMinPower', NaN, ...
    'hyperviscosityMaxPower', NaN, ...
    'iluRefreshes', NaN, ...
    'gmresSolves', NaN, ...
    'gmresIterations', NaN, ...
    'elapsedSeconds', NaN, ...
    'status', "", ...
    'message', "");
end
