function [problem, benchmark] = moving_surface_adr_tp_literature_problem(caseName)
%MOVING_SURFACE_ADR_TP_LITERATURE_PROBLEM Literature manufactured test cases.
%   Returns the closed-surface manufactured problems used by the literature
%   comparison sweeps, together with the published threshold that the
%   high-order RBF-FD method tries to match on the coarsest point cloud.

switch lower(string(caseName))
    case "de_stationary_sphere"
        benchmark = benchmarkEntry( ...
            "DziukElliott2007", ...
            "Stationary sphere heat equation", ...
            "Unit sphere, u=e^{-6t}x_1x_2, T=2", ...
            "P1 evolving surface FEM", ...
            "maxAbsL2Error", 1.2250e-3, ...
            "L^\infty(0,T;L^2) absolute error", ...
            0.036162, 0.036162^2, 2.0);
        problem = sphereProblem( ...
            "Dziuk-Elliott stationary sphere", ...
            benchmark.finalTime, ...
            @(t) 1.0, ...
            @(t) [0, 0, 0], ...
            @(t) eye(3), ...
            @(t, U) exp(-6 * t) .* U(:, 1) .* U(:, 2), ...
            @(t, U, mu) zeros(size(U, 1), 1), ...
            [0, 0, 0], ...
            @(t) 0.0);

    case "de_moving_ellipsoid"
        benchmark = benchmarkEntry( ...
            "DziukElliott2007", ...
            "Moving ellipsoid heat equation", ...
            "x_1^2/a(t)+x_2^2+x_3^2=1, a(t)=1+0.25 sin(t), u=e^{-6t}x_1x_2, T=4", ...
            "P1 evolving surface FEM", ...
            "maxAbsL2Error", 2.2950e-3, ...
            "L^\infty(0,T;L^2) absolute error", ...
            0.055007, 0.055007^2, 4.0);
        problem = movingEllipsoidProblem(benchmark.finalTime);

    case "ox_translating_sphere"
        benchmark = benchmarkEntry( ...
            "OlshanskiiXu2017", ...
            "Translating sphere", ...
            "Unit sphere translated by w=(0.2,0,0), u=1+e^{-2t}(x_1+x_2+x_3-0.2t), T=1", ...
            "P1 trace FEM with BDF2", ...
            "timeAbsL2L2Error", 1.040e-2, ...
            "L^2(0,T;L^2) absolute error", ...
            1/16, 1/64, 1.0);
        problem = sphereProblem( ...
            "Olshanskii-Xu translating sphere", ...
            benchmark.finalTime, ...
            @(t) 1.0, ...
            @(t) [0.2 * t, 0, 0], ...
            @(t) eye(3), ...
            @(t, U) 1 + exp(-2 * t) .* sum(U, 2), ...
            @(t, U, mu) zeros(size(U, 1), 1), ...
            [0, 0, 0], ...
            @(t) 4 * pi);

    case "ox_rotating_sphere"
        benchmark = benchmarkEntry( ...
            "OlshanskiiXu2017", ...
            "Rotating off-center sphere", ...
            "Unit sphere centered initially at (0.5,0,0), w=(-2*pi*x_2,2*pi*x_1,0), T=1", ...
            "P1 trace FEM with BDF2", ...
            "timeAbsL2L2Error", 7.36e-3, ...
            "L^2(0,T;L^2) absolute error", ...
            1/16, 1/512, 1.0);
        omega = 2 * pi;
        problem = sphereProblem( ...
            "Olshanskii-Xu rotating off-center sphere", ...
            benchmark.finalTime, ...
            @(t) 1.0, ...
            @(t) [0, 0, 0], ...
            @(t) rotationZ(omega * t), ...
            @(t, U) 1 + exp(-2 * t) .* sum(U, 2), ...
            @(t, U, mu) zeros(size(U, 1), 1), ...
            [0.5, 0, 0], ...
            @(t) 4 * pi);

    case "ox_shrinking_sphere"
        benchmark = benchmarkEntry( ...
            "OlshanskiiXu2017", ...
            "Shrinking sphere with source", ...
            "R(t)=e^{-t/2}, u=e^t(1+x_1x_2x_3), T=1", ...
            "P1 trace FEM with BDF2", ...
            "timeAbsL2L2Error", 3.038e-3, ...
            "L^2(0,T;L^2) absolute error", ...
            1/32, 1/128, 1.0);
        problem = sphereProblem( ...
            "Olshanskii-Xu shrinking sphere", ...
            benchmark.finalTime, ...
            @(t) exp(-0.5 * t), ...
            @(t) [0, 0, 0], ...
            @(t) eye(3), ...
            @shrinkingSphereExact, ...
            @shrinkingSphereForcing, ...
            [0, 0, 0], ...
            @(t) 4 * pi);

    otherwise
        error('kp:examples:UnknownLiteratureCase', ...
            'Unknown literature comparison case "%s".', caseName);
end
benchmark.caseName = string(caseName);
end

function benchmark = benchmarkEntry(sourceKey, name, setup, method, targetMetric, ...
    targetValue, targetDescription, publishedH, publishedDt, finalTime)
benchmark = struct( ...
    'caseName', "", ...
    'sourceKey', string(sourceKey), ...
    'benchmark', string(name), ...
    'setup', string(setup), ...
    'publishedMethod', string(method), ...
    'targetMetric', string(targetMetric), ...
    'targetValue', targetValue, ...
    'targetDescription', string(targetDescription), ...
    'publishedH', publishedH, ...
    'publishedDt', publishedDt, ...
    'finalTime', finalTime);
end

function problem = sphereProblem(label, finalTime, radius, center, rotation, exact, ...
    forcing, initialCenter, ~)
if nargin < 8
    initialCenter = [0, 0, 0];
end
problem.label = label;
problem.title = label;
problem.finalTime = finalTime;
problem.geometry = @(N, t) sphereGeometry(N, t, radius, center, rotation, initialCenter);
problem.geometryFromMaterial = @(material, t) sphereGeometryFromMaterial( ...
    material, t, radius, center, rotation, initialCenter);
problem.sampleMaterial = @(N, t) sphereMaterial(N);
problem.backtraceMaterial = @(material, tNow, tPast) material;
problem.exact = @(t, material) exact(t, material.U);
problem.forcing = @(t, material, mu) forcing(t, material.U, mu);
problem.exactMass = @(t, material, geom, ~) sum(geom.weights(:) .* exact(t, material.U));
end

function geom = sphereGeometry(N, t, radius, center, rotation, initialCenter)
geom = sphereGeometryFromMaterial(sphereMaterial(N), t, radius, center, rotation, initialCenter);
end

function material = sphereMaterial(N)
U = kp.geometry.fibonacciSphere(N);
U = U ./ max(vecnorm(U, 2, 2), eps);
material = struct('U', U);
end

function geom = sphereGeometryFromMaterial(material, t, radius, center, rotation, initialCenter)
U = material.U;
N = size(U, 1);
R = radius(t);
Q = rotation(t);
base = initialCenter + R .* U;
X = base * Q.' + center(t);
normals = U * Q.';
geom.X = X;
geom.normals = normals;
geom.weights = repmat(4 * pi * R^2 / N, N, 1);
geom.area = sum(geom.weights);
geom.h = sqrt(geom.area / N);
geom.material = struct('U', U, 'X', X);
end

function c = shrinkingSphereExact(t, U)
R = exp(-0.5 * t);
X = R .* U;
c = exp(t) .* (1 + prod(X, 2));
end

function f = shrinkingSphereForcing(t, U, mu) %#ok<INUSD>
R = exp(-0.5 * t);
X = R .* U;
p = prod(X, 2);
f = (-1.5 * exp(t) + 12 * exp(2 * t)) .* p;
end

function problem = movingEllipsoidProblem(finalTime)
problem.label = "Dziuk-Elliott moving ellipsoid";
problem.title = problem.label;
problem.finalTime = finalTime;
problem.geometry = @movingEllipsoidGeometry;
problem.geometryFromMaterial = @movingEllipsoidGeometryFromMaterial;
problem.sampleMaterial = @(N, t) sphereMaterial(N);
problem.backtraceMaterial = @(material, tNow, tPast) material;
problem.exact = @movingEllipsoidExact;
problem.forcing = @movingEllipsoidForcing;
problem.exactMass = @(t, material, geom, ~) ...
    sum(geom.weights(:) .* movingEllipsoidExact(t, material));
end

function geom = movingEllipsoidGeometry(N, t)
geom = movingEllipsoidGeometryFromMaterial(sphereMaterial(N), t);
end

function geom = movingEllipsoidGeometryFromMaterial(material, t)
U = material.U;
N = size(U, 1);
axesLengths = movingEllipsoidAxes(t);
X = U .* axesLengths;
g = X ./ (axesLengths .^ 2);
normals = g ./ max(vecnorm(g, 2, 2), eps);
geom.X = X;
geom.normals = normals;
geom.weights = ellipsoidSurfaceWeights(U, axesLengths);
geom.area = sum(geom.weights);
geom.h = sqrt(geom.area / N);
geom.material = struct('U', U, 'X', X);
end

function c = movingEllipsoidExact(t, material)
U = material.U;
axesLengths = movingEllipsoidAxes(t);
X = U .* axesLengths;
c = exp(-6 * t) .* X(:, 1) .* X(:, 2);
end

function f = movingEllipsoidForcing(t, material, mu)
U = material.U;
axesLengths = movingEllipsoidAxes(t);
axesPrime = movingEllipsoidAxesPrime(t);
X = U .* axesLengths;
V = U .* axesPrime;
geom = movingEllipsoidGeometryFromMaterial(material, t);
normal = geom.normals;
H = ellipsoidMeanCurvature(X, axesLengths);
lapX = -2 * H .* normal;
base = X(:, 1) .* X(:, 2);
c = exp(-6 * t) .* base;
materialDerivative = exp(-6 * t) .* (-6 * base + V(:, 1) .* X(:, 2) + X(:, 1) .* V(:, 2));
divv = linearMapSurfaceDivergence(U, axesLengths, axesPrime);
gradDot = -normal(:, 1) .* normal(:, 2);
lapBase = X(:, 2) .* lapX(:, 1) + X(:, 1) .* lapX(:, 2) + 2 * gradDot;
lapc = exp(-6 * t) .* lapBase;
f = materialDerivative + c .* divv - mu .* lapc;
end

function axesLengths = movingEllipsoidAxes(t)
a = 1 + 0.25 * sin(t);
axesLengths = [sqrt(a), 1, 1];
end

function axesPrime = movingEllipsoidAxesPrime(t)
a = 1 + 0.25 * sin(t);
ap = 0.25 * cos(t);
axesPrime = [0.5 * ap / sqrt(a), 0, 0];
end

function divv = linearMapSurfaceDivergence(U, axesLengths, axesPrime)
logDetRate = sum(axesPrime ./ axesLengths);
s2 = sum((U .^ 2) ./ (axesLengths .^ 2), 2);
logStretchRate = -sum((U .^ 2) .* (axesPrime ./ (axesLengths .^ 3)), 2) ./ s2;
divv = logDetRate + logStretchRate;
end

function H = ellipsoidMeanCurvature(X, axesLengths)
A = 1 ./ (axesLengths .^ 2);
g = X .* A;
s = vecnorm(g, 2, 2);
trA = sum(A);
gAg = sum((g .^ 2) .* A, 2);
divn = trA ./ s - gAg ./ (s .^ 3);
H = 0.5 * divn;
end

function area = ellipsoidAreaApprox(axesLengths)
p = 1.6075;
a = axesLengths(1);
b = axesLengths(2);
c = axesLengths(3);
area = 4 * pi * ((a^p * b^p + a^p * c^p + b^p * c^p) / 3)^(1 / p);
end

function weights = ellipsoidSurfaceWeights(U, axesLengths)
baseWeight = 4 * pi / size(U, 1);
jacobian = prod(axesLengths) .* vecnorm(U ./ axesLengths, 2, 2);
weights = baseWeight .* jacobian;
end

function Q = rotationZ(theta)
c = cos(theta);
s = sin(theta);
Q = [c, -s, 0; s, c, 0; 0, 0, 1];
end
