function study = moving_surface_adr_tp_spheroid_rearrangement_large_localtp_N4096()
%MOVING_SURFACE_ADR_TP_SPHEROID_REARRANGEMENT_LARGE_LOCALTP_N4096
%Run the large controlled-remap FPS/local-TP spheroid rearrangement case.

study = moving_surface_adr_tp_spheroid_rearrangement_study( ...
    'XiVals', [2, 4, 6], ...
    'NVals', 4096, ...
    'TransferModes', "localTp", ...
    'FinalTime', 0.35, ...
    'FlowScale', 0.8, ...
    'RearrangementTimes', 0.175, ...
    'MaterialSampler', "fps", ...
    'SamplerCandidateFactor', 8, ...
    'IncludeLagrangianComparison', false, ...
    'UseParallel', true, ...
    'OutputPrefix', fullfile(pwd, ...
        'moving_surface_adr_tp_spheroid_rearrangement_fps_localtp_N4096'), ...
    'ImageDir', fullfile(pwd, 'docs', 'figures'), ...
    'WriteFigures', false);

disp(study.table(:, {'xi', 'N', 'mode', 'transferMode', 'relerr', ...
    'numRearrangements', 'numFixedRearrangements', 'maxQuality', ...
    'elapsedSeconds'}));
end
