function study = moving_surface_adr_tp_parameter_sensitivity(varargin)
%MOVING_SURFACE_ADR_TP_PARAMETER_SENSITIVITY Small default-parameter sweep.
%   Uses the rotating breathing sphere at xi=4, N=1024 as the representative
%   moving-surface case.  The study varies defect-correction controls and
%   adaptive-hyperviscosity controls against matched direct/every-step
%   references.

parser = inputParser();
parser.addParameter('CaseName', "rotating_breathing_sphere");
parser.addParameter('Xi', 4, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('N', 1024, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('DtScale', 0.05, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('OutputPrefix', fullfile(pwd, 'moving_surface_adr_tp_parameter_sensitivity_xi4_N1024'));
parser.parse(varargin{:});
opts = parser.Results;

baseline = moving_surface_adr_tp_geometric_flow_suite(opts.CaseName, opts.Xi, opts.N, opts.DtScale, ...
    'DiffMatUpdateMethod', 'direct', ...
    'HyperviscosityUpdateMode', 'everyStep', ...
    'SpectrumCheck', false, ...
    'WriteOutputs', false);
baselineResult = baseline.results;

defectRows = runDefectSweep(opts, baselineResult.relerr);
hyperRows = runHyperviscositySweep(opts, baselineResult.relerr);

study = struct();
study.caseName = string(opts.CaseName);
study.xi = opts.Xi;
study.N = opts.N;
study.baselineError = baselineResult.relerr;
study.defectTable = struct2table(defectRows);
study.hyperviscosityTable = struct2table(hyperRows);

save(string(opts.OutputPrefix) + ".mat", 'study');
writetable(study.defectTable, string(opts.OutputPrefix) + "_defect.csv");
writetable(study.hyperviscosityTable, string(opts.OutputPrefix) + "_hyperviscosity.csv");
end

function rows = runDefectSweep(opts, baselineError)
tolerances = [1.0e-4, 1.0e-5, 1.0e-6];
iterations = [2, 3, 4];
rows = repmat(emptyDefectRow(), 0, 1);
rowIndex = 0;

for tol = tolerances
    for maxIt = iterations
        tic;
        run = moving_surface_adr_tp_geometric_flow_suite(opts.CaseName, opts.Xi, opts.N, opts.DtScale, ...
            'DiffMatUpdateMethod', 'defect', ...
            'DefectTolerance', tol, ...
            'MaxDefectIterations', maxIt, ...
            'HyperviscosityUpdateMode', 'everyStep', ...
            'SpectrumCheck', false, ...
            'WriteOutputs', false);
        elapsed = toc;
        R = run.results;
        stats = R.updateStats{1};
        rowIndex = rowIndex + 1;
        rows(rowIndex, 1) = struct( ...
            'defectTolerance', tol, ...
            'maxDefectIterations', maxIt, ...
            'time', elapsed, ...
            'relerr', R.relerr, ...
            'errorDifference', abs(R.relerr - baselineError), ...
            'updateDirect', stats.direct, ...
            'updateDefect', stats.defectCorrected, ...
            'updateFallback', stats.defectFailedRefactored, ...
            'maxResidual', stats.maxRelativeResidual, ...
            'meanDefectIterations', stats.meanDefectIterations);
    end
end
end

function rows = runHyperviscositySweep(opts, baselineError)
drifts = [0.02, 0.05, 0.10];
maxSkipped = [3, 5, 8];
rows = repmat(emptyHyperviscosityRow(), 0, 1);
rowIndex = 0;

for drift = drifts
    for skipped = maxSkipped
        tic;
        run = moving_surface_adr_tp_geometric_flow_suite(opts.CaseName, opts.Xi, opts.N, opts.DtScale, ...
            'DiffMatUpdateMethod', 'direct', ...
            'HyperviscosityUpdateMode', 'adaptiveGeometry', ...
            'HyperviscosityDriftTolerance', drift, ...
            'MaxHyperviscositySkippedSteps', skipped, ...
            'SpectrumCheck', false, ...
            'WriteOutputs', false);
        elapsed = toc;
        R = run.results;
        stats = R.updateStats{1};
        rowIndex = rowIndex + 1;
        rows(rowIndex, 1) = struct( ...
            'driftTolerance', drift, ...
            'maxSkippedSteps', skipped, ...
            'time', elapsed, ...
            'relerr', R.relerr, ...
            'errorDifference', abs(R.relerr - baselineError), ...
            'fullUpdates', stats.hyperviscosityFullUpdates, ...
            'predictedUpdates', stats.hyperviscosityPredictedUpdates, ...
            'maxRelativeDrift', stats.maxHyperviscosityRelativeDrift);
    end
end
end

function row = emptyDefectRow()
row = struct( ...
    'defectTolerance', NaN, ...
    'maxDefectIterations', 0, ...
    'time', NaN, ...
    'relerr', NaN, ...
    'errorDifference', NaN, ...
    'updateDirect', 0, ...
    'updateDefect', 0, ...
    'updateFallback', 0, ...
    'maxResidual', NaN, ...
    'meanDefectIterations', NaN);
end

function row = emptyHyperviscosityRow()
row = struct( ...
    'driftTolerance', NaN, ...
    'maxSkippedSteps', 0, ...
    'time', NaN, ...
    'relerr', NaN, ...
    'errorDifference', NaN, ...
    'fullUpdates', 0, ...
    'predictedUpdates', 0, ...
    'maxRelativeDrift', NaN);
end
