function study = moving_surface_adr_tp_literature_matched_xi2(varargin)
%MOVING_SURFACE_ADR_TP_LITERATURE_MATCHED_XI2 Resolution-matched comparison.
%   Runs xi=2 at a point count chosen from the published surface spacing,
%   using the published time step when T/dt is integral.  This is the
%   apples-to-apples low-order control for the xi=6 threshold comparison.

parser = inputParser();
parser.addParameter('Cases', ["de_stationary_sphere", "de_moving_ellipsoid", ...
    "ox_translating_sphere", "ox_rotating_sphere", "ox_shrinking_sphere"]);
parser.addParameter('Xi', 2, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('DtScale', 0.05, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('UseRearrangement', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('QualityThreshold', 1.55, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('PredictiveLookaheadSteps', 3, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('MinStepsBetweenRearrangements', 8, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('RearrangementTransferMode', "localTp", @(x) isstring(x) || ischar(x));
parser.addParameter('MassCorrectionMode', "balance", @(x) isstring(x) || ischar(x));
parser.addParameter('ExactStartup', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('GlobalGMRESTolerance', 1.0e-12, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
parser.addParameter('WarmParallelPool', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('ContinueOnError', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('SaveAfterEach', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('OutputPrefix', fullfile(pwd, ...
    'moving_surface_adr_tp_literature_matched_xi2'));
parser.parse(varargin{:});
opts = parser.Results;

if opts.WarmParallelPool
    warmParallelPool();
end

cases = string(opts.Cases(:).');
rows = repmat(emptyRow(), 0, 1);
for k = 1:numel(cases)
    [problem, benchmark] = moving_surface_adr_tp_literature_problem(cases(k));
    rows(k, 1) = runMatchedCase(problem, benchmark, opts);
    if opts.SaveAfterEach
        study = buildStudy(rows, opts);
        saveStudy(study, opts.OutputPrefix);
    end
end

study = buildStudy(rows, opts);
saveStudy(study, opts.OutputPrefix);
end

function warmParallelPool()
pool = gcp('nocreate');
if isempty(pool)
    parpool('Processes');
end
end

function row = runMatchedCase(problem, benchmark, opts)
row = emptyRow();
row.caseName = benchmark.caseName;
row.sourceKey = benchmark.sourceKey;
row.benchmark = benchmark.benchmark;
row.publishedMethod = benchmark.publishedMethod;
row.targetMetric = benchmark.targetMetric;
row.targetValue = benchmark.targetValue;
row.targetDescription = benchmark.targetDescription;
row.publishedH = benchmark.publishedH;
row.publishedDt = benchmark.publishedDt;
row.finalTime = benchmark.finalTime;
row.xi = opts.Xi;
row.normalMode = "calibratedSbf";

geom0 = problem.geometry(256, 0.0);
area0 = surfaceArea(geom0);
N = max(16, round(area0 / benchmark.publishedH^2));
row.N = N;
row.sqrtN = sqrt(N);
row.nominalMatchedN = N;
fixedDt = benchmark.publishedDt;

fprintf('\nMatched xi=2 literature case=%s N=%d published h=%.6e dt=%.6e\n', ...
    benchmark.caseName, N, benchmark.publishedH, fixedDt);

try
    tic;
    result = kp.manifold.runLagrangianMovingADRConvergence( ...
        problem, opts.Xi, N, opts.DtScale, ...
        'Mu', 1.0, ...
        'FinalTime', benchmark.finalTime, ...
        'FixedTimeStep', fixedDt, ...
        'DiffMatUpdateMethod', 'defect', ...
        'DefectTolerance', 1.0e-6, ...
        'MaxDefectIterations', 4, ...
        'NeighborUpdateMode', "periodic", ...
        'NeighborSearchInterval', 5, ...
        'SpectrumCheck', false, ...
        'HyperviscosityUpdateMode', 'adaptiveGeometry', ...
        'HyperviscosityDriftTolerance', 0.05, ...
        'MaxHyperviscositySkippedSteps', 5, ...
        'NormalMode', 'calibratedSbf', ...
        'GlobalSBFNormalDegree', 7, ...
        'GlobalSBFNormalOrder', 8, ...
        'GlobalSBFBalanceSafety', 0.1, ...
        'GlobalSBFControlPointScale', 1 / 3, ...
        'GlobalSBFMinControlPointCount', 48, ...
        'RecordMassDiagnostics', true, ...
        'TrackTimeErrors', true, ...
        'ExactStartup', opts.ExactStartup, ...
        'GlobalSolveMethod', "gmresIluDefect", ...
        'GlobalGMRESTolerance', opts.GlobalGMRESTolerance, ...
        'GlobalGMRESRestart', 40, ...
        'GlobalGMRESMaxIterations', 30, ...
        'GlobalDefectSweeps', 4, ...
        'GlobalILUDropTolerance', 1.0e-4, ...
        'UseRearrangement', opts.UseRearrangement, ...
        'QualityThreshold', opts.QualityThreshold, ...
        'PredictiveLookaheadSteps', opts.PredictiveLookaheadSteps, ...
        'MinStepsBetweenRearrangements', opts.MinStepsBetweenRearrangements, ...
        'RearrangementTransferMode', opts.RearrangementTransferMode, ...
        'MassCorrectionMode', opts.MassCorrectionMode);
    row.elapsedSeconds = toc;
    row.status = "ok";
    row.h = result.h;
    row.dt = result.dt;
    row.nsteps = result.nsteps;
    row.metricValue = metricValue(result, benchmark.targetMetric);
    row.success = isfinite(row.metricValue) && row.metricValue <= benchmark.targetValue;
    row.relativeToPublished = row.metricValue / benchmark.targetValue;
    row.effectiveSpacingRatio = row.h / benchmark.publishedH;
    row.timeStepRatio = row.dt / benchmark.publishedDt;
    row.finalRelL2Error = result.finalRelL2Error;
    row.finalAbsL2Error = result.finalAbsL2Error;
    row.maxRelL2Error = result.maxRelL2Error;
    row.maxAbsL2Error = result.maxAbsL2Error;
    row.timeRelL2L2Error = result.timeRelL2L2Error;
    row.timeAbsL2L2Error = result.timeAbsL2L2Error;
    row.massRelError = result.massRelError;
    row.balanceRelResidual = result.balanceRelResidual;
    row.massCorrectionSteps = result.massCorrectionSteps;
    row.massCorrectionMaxRelative = result.massCorrectionMaxRelative;
    row.massCorrectionMaxPointShift = result.massCorrectionMaxPointShift;
    row.normalRMSAngle = result.normalRMSAngle;
    row.normalMaxAngle = result.normalMaxAngle;
    row.normalControlPointCount = result.normalControlPointCount;
    row.normalControlPointFraction = result.normalControlPointFraction;
    row.numRearrangements = result.numRearrangements;
    row.initialQuality = result.initialQuality;
    row.finalQuality = result.finalQuality;
    row.maxQuality = result.maxQuality;
    stats = result.updateStats{1};
    row.updateDirect = stats.direct;
    row.updateDefectCorrected = stats.defectCorrected;
    row.updateFallback = stats.defectFailedRefactored;
    solveStats = result.solveStats{1};
    row.iluRefreshes = solveStats.iluRefreshes;
    row.gmresSolves = solveStats.gmresSolves;
    row.gmresIterations = solveStats.gmresIterations;
    row.hyperviscosityMinPower = stats.minHyperviscosityPower;
    row.hyperviscosityMaxPower = stats.maxHyperviscosityPower;
    fprintf('  metric=%.6e target=%.6e ratio=%.3f h/h_lit=%.3f dt/dt_lit=%.3f\n', ...
        row.metricValue, row.targetValue, row.relativeToPublished, ...
        row.effectiveSpacingRatio, row.timeStepRatio);
catch ME
    row.elapsedSeconds = toc;
    row.status = "failed";
    row.message = string(ME.message);
    fprintf('  FAILED: %s\n', ME.message);
    if ~opts.ContinueOnError
        rethrow(ME);
    end
end
end

function area = surfaceArea(geom)
if isfield(geom, 'area') && ~isempty(geom.area)
    area = geom.area;
elseif isfield(geom, 'h') && ~isempty(geom.h)
    area = geom.h^2 * size(geom.X, 1);
else
    error('kp:examples:MissingSurfaceArea', ...
        'Geometry must provide area or h to compute matched N.');
end
end

function value = metricValue(result, metricName)
switch string(metricName)
    case "maxAbsL2Error"
        value = result.maxAbsL2Error;
    case "timeAbsL2L2Error"
        value = result.timeAbsL2L2Error;
    case "finalAbsL2Error"
        value = result.finalAbsL2Error;
    case "finalRelL2Error"
        value = result.finalRelL2Error;
    otherwise
        error('kp:examples:BadLiteratureMetric', ...
            'Unknown literature comparison metric "%s".', metricName);
end
end

function study = buildStudy(rows, opts)
study = struct();
study.table = struct2table(rows);
study.xi = opts.Xi;
study.comparisonType = "matchedResolution";
study.normalMode = "calibratedSbf";
study.diffMatUpdateMethod = "defect";
study.hyperviscosityUpdateMode = "adaptiveGeometry";
study.globalSolveMethod = "gmresIluDefect";
study.massCorrectionMode = string(opts.MassCorrectionMode);
end

function saveStudy(study, outputPrefix)
save(string(outputPrefix) + ".mat", 'study');
writetable(study.table, string(outputPrefix) + ".csv");
end

function row = emptyRow()
row = struct( ...
    'caseName', "", ...
    'sourceKey', "", ...
    'benchmark', "", ...
    'publishedMethod', "", ...
    'targetMetric', "", ...
    'targetDescription', "", ...
    'targetValue', NaN, ...
    'publishedH', NaN, ...
    'publishedDt', NaN, ...
    'finalTime', NaN, ...
    'xi', NaN, ...
    'N', NaN, ...
    'sqrtN', NaN, ...
    'nominalMatchedN', NaN, ...
    'h', NaN, ...
    'dt', NaN, ...
    'nsteps', NaN, ...
    'normalMode', "", ...
    'metricValue', NaN, ...
    'success', false, ...
    'relativeToPublished', NaN, ...
    'effectiveSpacingRatio', NaN, ...
    'timeStepRatio', NaN, ...
    'finalRelL2Error', NaN, ...
    'finalAbsL2Error', NaN, ...
    'maxRelL2Error', NaN, ...
    'maxAbsL2Error', NaN, ...
    'timeRelL2L2Error', NaN, ...
    'timeAbsL2L2Error', NaN, ...
    'massRelError', NaN, ...
    'balanceRelResidual', NaN, ...
    'massCorrectionSteps', NaN, ...
    'massCorrectionMaxRelative', NaN, ...
    'massCorrectionMaxPointShift', NaN, ...
    'normalRMSAngle', NaN, ...
    'normalMaxAngle', NaN, ...
    'normalControlPointCount', NaN, ...
    'normalControlPointFraction', NaN, ...
    'numRearrangements', NaN, ...
    'initialQuality', NaN, ...
    'finalQuality', NaN, ...
    'maxQuality', NaN, ...
    'updateDirect', NaN, ...
    'updateDefectCorrected', NaN, ...
    'updateFallback', NaN, ...
    'hyperviscosityMinPower', NaN, ...
    'hyperviscosityMaxPower', NaN, ...
    'iluRefreshes', NaN, ...
    'gmresSolves', NaN, ...
    'gmresIterations', NaN, ...
    'elapsedSeconds', NaN, ...
    'status', "", ...
    'message', "");
end
