function capstone = moving_surface_adr_tp_rbc_capstone(varargin)
%MOVING_SURFACE_ADR_TP_RBC_CAPSTONE Passive transport on a fluid-driven RBC.
%   The membrane trajectory is generated by the companion 3D IBAMR FSI
%   application. This driver advances a source-free surface
%   advection-diffusion problem using the production moving-surface method.

parser = inputParser();
repoRoot = fileparts(fileparts(mfilename('fullpath')));
parser.addParameter('TrajectoryDirectory', ...
    fullfile(repoRoot, 'data', 'ibamr_rbc_3d', 'trajectory'));
parser.addParameter('Xi', 6, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('Mu', 2.0e-3, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('TimeStep', NaN, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('FinalTime', NaN, @(x) isnumeric(x) && isscalar(x));
parser.addParameter('StencilSizeFactor', 1.0, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
parser.addParameter('DiffMatUpdateMethod', "defect", ...
    @(x) isstring(x) || ischar(x));
parser.addParameter('DefectTolerance', 1.0e-6, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
parser.addParameter('WriteFigures', true, @(x) islogical(x) && isscalar(x));
parser.addParameter('RedrawOnly', false, @(x) islogical(x) && isscalar(x));
parser.addParameter('VisualizationPointCount', 10000, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
parser.addParameter('FigureDirectory', fullfile(repoRoot, 'docs', 'figures'));
parser.addParameter('OutputPrefix', fullfile(repoRoot, 'moving_surface_adr_tp_rbc_capstone'));
parser.parse(varargin{:});
opts = parser.Results;

if ~isfolder(opts.TrajectoryDirectory)
    error('kp:examples:MissingRBCTrajectory', ...
        ['The RBC trajectory is not installed. Run ' ...
         'download_rbc_capstone_data from the repository root.']);
end

trajectory = kp.manifold.IBAMRSurfaceTrajectory(opts.TrajectoryDirectory, ...
    'Xi', opts.Xi, 'Degree', 7);
if opts.RedrawOnly
    saved = load(string(opts.OutputPrefix) + ".mat", 'capstone');
    capstone = saved.capstone;
    capstone.figurePaths = writeCapstoneFigures(capstone, trajectory, ...
        opts.FigureDirectory, opts.VisualizationPointCount);
    return;
end
N = size(trajectory.MaterialSites, 1);
if isnan(opts.FinalTime)
    finalTime = trajectory.Times(end);
else
    finalTime = min(opts.FinalTime, trajectory.Times(end));
end

problem = capstoneProblem(trajectory, N, finalTime);
initialGeometry = problem.geometry(N, 0);
maximumTimeStep = initialGeometry.h ^ (opts.Xi / 3);
if isnan(opts.TimeStep)
    nsteps = ceil(finalTime / (0.9 * maximumTimeStep));
    timeStep = finalTime / max(nsteps, 3);
else
    timeStep = opts.TimeStep;
    if timeStep > maximumTimeStep
        error('kp:examples:RBCCapstoneTimeStepTooLarge', ...
            ['TimeStep %.3e violates dt^3 <= h^xi; use at most %.3e ' ...
            'for xi=%d and h=%.3e.'], ...
            timeStep, maximumTimeStep, opts.Xi, initialGeometry.h);
    end
end
results = kp.manifold.runLagrangianMovingADRConvergence( ...
    problem, opts.Xi, N, 0.05, ...
    'Mu', opts.Mu, ...
    'FinalTime', finalTime, ...
    'FixedTimeStep', timeStep, ...
    'DiffMatUpdateMethod', string(opts.DiffMatUpdateMethod), ...
    'StencilSizeFactor', opts.StencilSizeFactor, ...
    'DefectTolerance', opts.DefectTolerance, ...
    'MaxDefectIterations', 4, ...
    'NeighborUpdateMode', 'reuse', ...
    'NeighborSearchInterval', 5, ...
    'SpectrumCheck', true, ...
    'HyperviscosityUpdateMode', 'adaptiveGeometry', ...
    'NormalMode', 'provided', ...
    'GlobalSolveMethod', 'gmresIluDefect', ...
    'GlobalDefectSweeps', 4, ...
    'GlobalILUDropTolerance', 1.0e-4, ...
    'GlobalILURefreshInterval', Inf, ...
    'MassCorrectionMode', 'balance', ...
    'MassCorrectionMaxRelativeCorrection', 5.0e-2, ...
    'UseRearrangement', true, ...
    'QualityThreshold', 2.3, ...
    'PredictiveLookaheadSteps', 3, ...
    'MinStepsBetweenRearrangements', 8, ...
    'RearrangementTransferMode', 'localTp', ...
    'ReturnSolution', true);

initialMaterial = initialGeometry.material;
initialConcentration = initialTracer(initialMaterial);
if isfield(results(1), 'solution') && ~isempty(results(1).solution)
    finalConcentration = results(1).solution{1};
else
    finalConcentration = [];
end
if isfield(results(1), 'finalGeometry') && ~isempty(results(1).finalGeometry)
    finalGeometry = results(1).finalGeometry{1};
else
    finalGeometry = trajectory.geometry(initialMaterial, finalTime);
end

capstone = struct();
capstone.results = results;
capstone.trajectoryDiagnostics = trajectory.Diagnostics;
capstone.velocityInterpolation = trajectory.validateVelocityInterpolation();
capstone.geometryControlInfo = trajectory.ControlInfo;
capstone.initial = struct('time', 0, 'geometry', initialGeometry, ...
    'concentration', initialConcentration);
capstone.final = struct('time', finalTime, 'geometry', finalGeometry, ...
    'concentration', finalConcentration);
capstone.figurePaths = strings(0, 1);
% Persist the completed solve before optional rendering so a graphics or
% export failure cannot discard a long-running production trajectory.
save(string(opts.OutputPrefix) + ".mat", 'capstone', '-v7.3');
if opts.WriteFigures
    if ~isfolder(opts.FigureDirectory)
        mkdir(opts.FigureDirectory);
    end
    capstone.figurePaths = writeCapstoneFigures(capstone, trajectory, ...
        opts.FigureDirectory, opts.VisualizationPointCount);
    save(string(opts.OutputPrefix) + ".mat", 'capstone', '-v7.3');
end
relativeMassChange = abs(results.finalMass - results.initialMass) / ...
    max(abs(results.initialMass), eps);
summary = table(opts.Xi, N, opts.Mu, results.dt, finalTime, ...
    results.finalMass, results.initialMass, relativeMassChange, ...
    results.balanceRelResidual, results.numRearrangements, ...
    capstone.velocityInterpolation.relativeRMS, ...
    'VariableNames', {'xi', 'N', 'mu', 'dt', 'final_time', ...
    'final_mass', 'initial_mass', 'relative_mass_error', ...
    'mass_balance_residual', 'rearrangements', ...
    'velocity_interpolation_relative_rms'});
writetable(summary, string(opts.OutputPrefix) + ".csv");
end

function problem = capstoneProblem(trajectory, N, finalTime)
problem = struct();
problem.label = "Passive transport on a fluid-driven red blood cell";
problem.title = "Transport on a fluid-driven red blood cell";
problem.finalTime = finalTime;
problem.geometry = @(requestedN, t) nativeGeometry(trajectory, requestedN, N, t);
problem.geometryFromMaterial = @(material, t) trajectory.geometry(material, t);
problem.sampleMaterial = @(requestedN, t) trajectory.sampleMaterial(requestedN, t);
problem.backtraceMaterial = @(material, tNow, tPast) material;
problem.initial = @initialTracer;
problem.forcing = @(t, material, mu) zeros(size(material.U, 1), 1);
problem.massRate = @(t, material, geom, mu) 0;
end

function geom = nativeGeometry(trajectory, requestedN, nativeN, t)
if requestedN ~= nativeN
    error('kp:examples:BadRBCCapstoneResolution', ...
        'The capstone is configured for %d PDE markers, not %d.', nativeN, requestedN);
end
material = trajectory.sampleMaterial(requestedN, t);
geom = trajectory.geometry(material, t);
end

function c = initialTracer(material)
U = material.U;
center1 = normalizeRow([0.25, 0.80, 0.54]);
center2 = normalizeRow([-0.55, -0.20, 0.81]);
distance1 = acos(min(max(U * center1.', -1), 1));
distance2 = acos(min(max(U * center2.', -1), 1));
c = 1.0 + exp(-(distance1 / 0.28) .^ 2) + ...
    0.65 * exp(-(distance2 / 0.22) .^ 2);
end

function paths = writeCapstoneFigures(capstone, trajectory, figureDirectory, visualizationPointCount)
paths = strings(2, 1);
paths(1) = fullfile(figureDirectory, 'moving_surface_adr_tp_rbc_capstone_transport.png');
paths(2) = fullfile(figureDirectory, 'moving_surface_adr_tp_rbc_capstone_motion.png');

times = [trajectory.Times(1), trajectory.Times(round((numel(trajectory.Times) + 1) / 2)), ...
    trajectory.Times(end)];
visualizationMaterial = trajectory.sampleMaterial(visualizationPointCount, times(2));
geometries = cell(3, 1);
triangles = cell(3, 1);
for k = 1:3
    geometries{k} = trajectory.geometry(visualizationMaterial, times(k));
    triangles{k} = kp.geometry.triangulateClosedSurface(geometries{k}.X);
end
sourceMaterial = capstone.initial.geometry.material;
denseConcentrations = trajectory.interpolateMaterialField(sourceMaterial, ...
    [capstone.initial.concentration, capstone.final.concentration], ...
    visualizationMaterial);
limits = sharedSpatialLimits(geometries);

fig = figure('Color', 'w', 'Position', [100, 100, 1260, 520]);
layout = tiledlayout(1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
colorLimits = [min(denseConcentrations, [], 'all'), max(denseConcentrations, [], 'all')];
plotTracer(nexttile, geometries{1}, triangles{1}, denseConcentrations(:, 1), ...
    'Initial concentration', colorLimits, geometryLimits(geometries{1}.X));
finalAxes = nexttile;
plotTracer(finalAxes, geometries{3}, triangles{3}, denseConcentrations(:, 2), ...
    'Final concentration', colorLimits, geometryLimits(geometries{3}.X));
colorScale = colorbar(finalAxes);
colorScale.Layout.Tile = 'east';
ylabel(colorScale, '$c$', 'Interpreter', 'latex', 'FontWeight', 'bold');
title(layout, 'Chemical concentration on the moving membrane', ...
    'FontSize', 16, 'FontWeight', 'bold');
exportPaperFigure(fig, paths(1));
close(fig);

fig = figure('Color', 'w', 'Position', [100, 100, 1400, 620]);
motionLayout = tiledlayout(fig, 1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
ax = nexttile(motionLayout);
hold(ax, 'on');
surfaceHandles = gobjects(3, 1);
surfaceColors = [0.93, 0.55, 0.50; 0.82, 0.20, 0.18; 0.55, 0.02, 0.06];
for k = 1:3
    geom = geometries{k};
    surfaceHandles(k) = trisurf(triangles{k}, geom.X(:, 1), geom.X(:, 2), geom.X(:, 3), ...
        'Parent', ax, 'EdgeColor', 'none', 'FaceColor', surfaceColors(k, :), ...
        'DisplayName', sprintf('$t=%.2f$', times(k)));
    set(surfaceHandles(k), 'VertexNormals', geom.normals, ...
        'FaceLighting', 'gouraud', 'AmbientStrength', 0.55, ...
        'DiffuseStrength', 0.65, 'SpecularStrength', 0.08);
end
formatSurfaceAxes(ax, limits);
camlight(ax, 'headlight');
legend(ax, surfaceHandles, 'Interpreter', 'latex', 'Location', 'southoutside', ...
    'Orientation', 'horizontal', 'NumColumns', 3);
title(ax, 'Translation in the channel', 'FontSize', 16, 'FontWeight', 'bold');

centeredGeometries = cell(3, 1);
for k = 1:3
    centeredGeometries{k} = geometries{k};
    centeredGeometries{k}.X = geometries{k}.X - mean(geometries{k}.X, 1);
end
centeredLimits = sharedSpatialLimits(centeredGeometries);
centeredAxes = nexttile(motionLayout);
hold(centeredAxes, 'on');
centeredHandles = gobjects(3, 1);
for k = 1:3
    geom = centeredGeometries{k};
    centeredHandles(k) = trisurf(triangles{k}, ...
        geom.X(:, 1), geom.X(:, 2), geom.X(:, 3), ...
        'Parent', centeredAxes, 'EdgeColor', 'none', ...
        'FaceColor', surfaceColors(k, :), ...
        'DisplayName', sprintf('$t=%.2f$', times(k)));
    set(centeredHandles(k), 'VertexNormals', geometries{k}.normals, ...
        'FaceLighting', 'gouraud', 'AmbientStrength', 0.55, ...
        'DiffuseStrength', 0.65, 'SpecularStrength', 0.08);
end
formatSurfaceAxes(centeredAxes, centeredLimits);
camlight(centeredAxes, 'headlight');
title(centeredAxes, 'Centroid-aligned deformation', ...
    'FontSize', 16, 'FontWeight', 'bold');
title(motionLayout, 'Fluid-driven red blood cell motion', ...
    'FontSize', 17, 'FontWeight', 'bold');
exportPaperFigure(fig, paths(2));
close(fig);
end

function plotTracer(ax, geom, triangles, concentration, titleText, colorLimits, limits)
trisurf(triangles, geom.X(:, 1), geom.X(:, 2), geom.X(:, 3), concentration, ...
    'Parent', ax, 'EdgeColor', 'none');
shading(ax, 'interp');
formatSurfaceAxes(ax, limits);
clim(ax, colorLimits);
title(ax, titleText, 'FontSize', 14, 'FontWeight', 'bold');
colormap(ax, turbo);
end

function limits = sharedSpatialLimits(geometries)
points = cell2mat(cellfun(@(geom) geom.X, geometries, 'UniformOutput', false));
minimum = min(points, [], 1);
maximum = max(points, [], 1);
padding = 0.08 * max(maximum - minimum, eps);
limits = [minimum - padding; maximum + padding];
end

function limits = geometryLimits(points)
minimum = min(points, [], 1);
maximum = max(points, [], 1);
padding = 0.08 * max(maximum - minimum, eps);
limits = [minimum - padding; maximum + padding];
end

function formatSurfaceAxes(ax, limits)
axis(ax, 'equal');
xlim(ax, limits(:, 1));
ylim(ax, limits(:, 2));
zlim(ax, limits(:, 3));
view(ax, 42, 24);
grid(ax, 'on');
xlabel(ax, '$x_1$', 'Interpreter', 'latex', 'FontWeight', 'bold');
ylabel(ax, '$x_2$', 'Interpreter', 'latex', 'FontWeight', 'bold');
zlabel(ax, '$x_3$', 'Interpreter', 'latex', 'FontWeight', 'bold');
end

function exportPaperFigure(fig, path)
set(findall(fig, '-property', 'FontSize'), 'FontSize', 14);
set(findall(fig, '-property', 'FontWeight'), 'FontWeight', 'bold');
if exist('export_fig', 'file') ~= 2
    error('kp:examples:MissingExportFig', ...
        'Paper figures require export_fig on the MATLAB path.');
end
export_fig(fig, char(path), '-png', '-r300', '-transparent');
end

function x = normalizeRow(x)
x = x ./ norm(x);
end
